# Generated by Django 4.2.3 on 2023-07-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
