# Generated by Django 4.2.3 on 2023-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='appuser',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
    ]
