# Generated by Django 4.2.3 on 2023-07-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appuser_first_name_appuser_status_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_number', models.CharField(max_length=10)),
                ('ciloxis_num', models.CharField(max_length=50)),
                ('proj_concat', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='proj_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project'),
        ),
    ]
