# Generated by Django 4.2.3 on 2023-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_booking_proj_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
