# Generated by Django 4.2.3 on 2023-07-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_num_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
