# Generated by Django 4.2.3 on 2023-08-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_booking_group_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status_active', models.BooleanField(default=True)),
                ('centres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchcentres')),
            ],
        ),
    ]
