# Generated by Django 4.2.3 on 2023-08-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_researchgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchgroup'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchgroup'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
