# Generated by Django 4.2.3 on 2023-08-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_prestartcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_equip',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_group', models.CharField(max_length=250)),
                ('equip_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.equipment')),
            ],
        ),
    ]
