# Generated by Django 4.2.3 on 2023-08-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_equipment_is_equip_equipmentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentgroup',
            name='equip_name',
        ),
    ]
