# Generated by Django 4.2.3 on 2023-08-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_equipment_equip_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestartcheck',
            name='anti_slip',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='prestartcheck',
            name='filter_mat',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='prestartcheck',
            name='noise_baffles',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
