# Generated by Django 4.2.3 on 2023-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_prestartcheck_glass_bott_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestartcheck',
            name='hyd_oil_level',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
