# Generated by Django 4.2.3 on 2023-08-26 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_prestartcheck_rubber_strap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['user_name__username']},
        ),
        migrations.AlterField(
            model_name='prestartcheck',
            name='prestart_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
