# Generated by Django 4.2.3 on 2023-08-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_prestartcheck_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('sample_status', models.CharField(blank=True, choices=[('Not Received', 'Not Received'), ('Received', 'Received'), ('Disposed', 'Disposed'), ('Returned', 'Returned'), ('Quarantine', 'Quarantine')], max_length=25)),
                ('centre_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchcentres')),
                ('client_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client')),
                ('group_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.researchgroup')),
                ('sample_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location')),
                ('sample_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.appuser')),
            ],
        ),
    ]
