# Generated by Django 4.2.3 on 2023-08-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='hazard_advice',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
