# Generated by Django 4.2.3 on 2023-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sample_hazard_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
