# Generated by Django 4.2.3 on 2023-08-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_sample_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestartcheck',
            name='battery_condition',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10),
        ),
        migrations.AddField(
            model_name='prestartcheck',
            name='battery_water',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10),
        ),
        migrations.AddField(
            model_name='prestartcheck',
            name='counter',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10),
        ),
        migrations.AddField(
            model_name='prestartcheck',
            name='safety_stop',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10),
        ),
    ]
