# Generated by Django 4.2.3 on 2023-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_equipment_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='ute_auth',
            field=models.BooleanField(default=False),
        ),
    ]
