# Generated by Django 4.2.3 on 2023-09-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_clientsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=350)),
                ('client_number', models.IntegerField()),
                ('client_email', models.CharField(max_length=500)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client')),
                ('site_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clientsite')),
            ],
        ),
    ]
