# Generated by Django 4.2.3 on 2023-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_sample_sample_location_sample_sample_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestartcheck',
            name='cable',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_location',
            field=models.ManyToManyField(blank=True, to='main.location'),
        ),
    ]
