# Generated by Django 4.2.3 on 2023-12-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_booking_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shift',
            field=models.CharField(blank=True, choices=[('', '-----'), ('All Day', 'All Day'), ('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='All Day', max_length=50),
        ),
    ]
